services:
  tfg_nvidia:
    extends:
      file: docker-compose-gui.yaml
      service: tfg
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia