controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [dummy]
    dummy:
      rt_freq: 30.0
      plugin: easynav_controller/DummyController
      cycle_time_nort: 0.01
      cycle_time_rt: 0.001


# localizer_node:
#   ros__parameters:
#     use_sim_time: true
#     localizer_types: [amcl]
#     amcl:
#       rt_freq: 50.0
#       freq: 5.0
#       reseed_freq: 0.1
#       plugin: easynav_navmap_localizer/AMCLLocalizer
#       num_particles: 100
#       noise_translation: 0.1
#       noise_rotation: 0.03
#       noise_translation_to_rotation: 0.02
#       min_noise_xy: 0.2
#       min_noise_yaw: 0.1
#       compute_odom_from_tf: true 
#       initial_pose:
#         x: 0.0
#         y: 0.0
#         yaw: 0.0
#         std_dev_xy: 0.05
#         std_dev_yaw: 0.01

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [dummy]
    dummy:
      rt_freq: 50.0
      freq: 5.0
      reseed_freq: 0.1
      plugin: easynav_localizer/DummyLocalizer
      cycle_time_nort: 0.01
      cycle_time_rt: 0.001

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [bonxai, navmap]
    bonxai:
      freq: 10.0
      plugin: easynav_bonxai_maps_manager/BonxaiMapsManager
      package: drone_pkg
      bonxai_path_file: maps/new_bonxai_map.pcd
    navmap:
      freq: 10.0
      plugin: easynav_navmap_maps_manager/NavMapMapsManager
      package: drone_pkg
      # navmap_path_file: maps/map.navmap

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [dummy]
    dummy:
      freq: 1.0
      plugin: easynav_planner/DummyPlanner
      cycle_time_nort: 0.2
      cycle_time_rt: 0.001

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    perception_default_frame: odom

system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    position_tolerance: 0.3
    angle_tolerance: 0.15